spring:
  profiles:
    active: dev
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/localdev_db}
    username: ${DB_USER:postgres_user}
    password: ${DB_PASSWORD:postgres_pass}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
server:
  port: 8080
logging:
  level:
    root: INFO                           # Base level for everything
    gr.seo.youthapp: DEBUG                   # Log business logic
    org.springframework.web: DEBUG       # Log web requests/responses
    org.hibernate.SQL: DEBUG             # Log generated SQL statements
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE  # Log query parameters
  file:
    name: logs/youthapp.log              # Log to file
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"